export const meta = {
  name: 'nexusops-draft-verify',
  description: 'Draft and adversarially verify the 7 remaining platform-architecture documents',
  phases: [
    { title: 'Draft', detail: '7 parallel document drafters' },
    { title: 'Verify', detail: 'consistency + code-grounding audit per doc' },
    { title: 'Fix', detail: 'repair verified issues' },
  ],
}

const SPINE = [
  'READ FIRST (the approved spine - your doc MUST be consistent with these):',
  '- docs/platform-vision.md (direction, principles, control/data plane, wedge)',
  '- docs/domain-model.md (entities, org scoping, environment promotion, Node=Server rename)',
  '- docs/multi-tenancy.md (X-Org-Id resolution, session guard, channels, agents, IDOR suite)',
  '- docs/authorization.md (registry changes, 5 roles, grants design, NO node.execute)',
  '',
  'Then read .claude/workflows/findings.json - structured subsystem reports from an earlier',
  'analysis phase (11 reports; read the ones relevant to your doc). Current-state claims in',
  'your doc must agree with those reports (they carry path:line evidence).',
  '',
  'Repo: /home/emad/projects/nexusops. If you need to verify a specific code detail, orient',
  'with the graphify graph first: $(cat graphify-out/.graphify_python) -m graphify query "question" --budget 1500',
  '',
  'Rules for the doc you write:',
  '- Ground current-state claims in the actual repo (path:line). Future-state sections are design specs.',
  '- NEVER present a simulated capability as real; label the simulated runner/sim transports explicitly.',
  '- Consistency vocabulary: Organization/Membership/Node(=Server)/Project/Environment(project-scoped)/',
  '  Domain/Route/Certificate/Operation/Secret/SecretVersion. Permission codenames per authorization.md.',
  '- The agent pulls; no remote shell; operations are whitelisted types.',
  '- Terse, tables over prose, 250-450 lines, mermaid diagrams where they clarify (sequence/flow).',
  '- Long docs: write in pieces — an initial Write with the skeleton, then Edit appends per section.',
  '  Avoid very wide check-mark matrices (they corrupt generation). Keep tables under ~6 columns.',
  '- Sections: use the Required sections list in your task; end with "## Open questions" (real unresolved decisions only).',
  '- Write ONLY the single doc file named in your task. Do not modify code or any other file.',
  '- Do not paste large verbatim code listings; short illustrative snippets are fine.',
].join('\n')

const VERIFY_RULES = [
  'You are auditing one architecture document for the NexusOps multi-tenant redesign.',
  'Repo: /home/emad/projects/nexusops.',
  'Read: the doc named below, the four spine docs (docs/platform-vision.md, docs/domain-model.md,',
  'docs/multi-tenancy.md, docs/authorization.md), and .claude/workflows/findings.json.',
  'Check and report issues:',
  '1. CONSISTENCY: entity names, phase numbering, permission codenames, org-scoping statements must',
  '   match the spine docs exactly. Flag any contradiction.',
  '2. CODE GROUNDING: spot-check up to 10 current-state code references (path:line) in the doc (as',
  '   many as exist - new-subsystem docs have few current-state references). Orient with graphify',
  '   first: $(cat graphify-out/.graphify_python) -m graphify query "..." --budget 1200.',
  '   Flag references that do not exist or say something different.',
  '3. HONESTY: any place a simulated/partial capability is presented as real. The deployment runner',
  '   is SIMULATED today; sim:// monitors and docker_sim are simulation tooling.',
  '4. COVERAGE: which required topics from the task below are missing or thin.',
  '5. SECURITY: any design statement that would break tenant isolation, leak secrets, or add an',
  '   uncontrolled remote-execution surface.',
  'Do not edit any file. Report issues only. If the doc is solid, return an empty issues list.',
].join('\n')

const DOCS = [
  {
    file: 'docs/node-agent-architecture.md',
    task: [
      'DOC: docs/node-agent-architecture.md - Node & agent architecture.',
      'Required sections: Node concept (= existing Server entity, rename at API/UI layer, capabilities,',
      'facts, docker endpoint 0..1 relation); agent lifecycle (enrollment v2 with org-scoped single-use',
      'enrollment tokens replacing the global env-var token, token storage, rotation with dual-token',
      'grace, revocation semantics incl. fixing the 401 hot-loop, reconnect/offline states); heartbeat',
      'contract v2 (existing hello/heartbeat fields + capabilities + agent version reporting via',
      'User-Agent or hello); the Operations framework - pull model (agent polls), Operation row',
      'lifecycle, WHITELISTED op types table (container.start/stop/restart/remove, logs.tail,',
      'nginx.render/apply/reload - nothing else), per-op authorization mapping, timeouts, result',
      'reporting, audit; agent security (token scope, docker.sock root-equivalence, transport HTTPS-',
      'only, no arbitrary exec); versioning/upgrades (control plane sees agent version, out-of-date',
      'warning, future self-update); install UX (install.sh today and target one-liner).',
      'Use a mermaid sequence diagram for: enrollment, and: operation dispatch end-to-end.',
      'Key current-state facts to build on (from findings agent-4/agent-0): per-server nxa_ token',
      'hashed in Server.agent_token_hash; heartbeat ~30s; AGENT_CONTAINER_CAP; ensure_docker_host;',
      'AgentHelloOut negotiation channel; Server.extra JSONB for facts; stolen token = permanent write',
      'cred to one server today.',
    ].join('\n'),
  },
  {
    file: 'docs/domain-routing.md',
    task: [
      'DOC: docs/domain-routing.md - Domains and reverse-proxy management.',
      'Required sections: the Domain/Route/Certificate entity model (per domain-model.md 2.4); DNS',
      'ownership verification (TXT token, anti-takeover: verify before any route goes live, re-verify',
      'on apex change); where nginx runs (ON the customer node, agent-managed; control plane never in',
      'customer traffic path; dashboard edge only serves the dashboard); the ProxyProvider interface',
      '(render/apply/status; NginxProvider first impl; future Traefik/Caddy); config rendering',
      '(templates with STRICT allowlists - no user-supplied raw nginx directives in v1; injection',
      'threat); apply pipeline via agent operation: write staged config, nginx -t validate, atomic',
      'swap, reload, rollback on failure; upstream binding (route -> node + container:port; what',
      'happens when container moves/restarts - re-render triggers); headers/rate-limit/redirect',
      'config; wildcard domains and catch-all behavior; how deployments hook routing (post-deploy',
      'route sync); user journey: add domain, verify, create route, HTTPS (point to certificate doc).',
      'Mermaid: sequence for add-domain-to-verified; flow for config apply with rollback.',
      'Current-state grounding: there is NO domain/nginx code today; the nginx/ dir and edge config',
      'in the repo serve the DASHBOARD (from findings agent-2) - say so explicitly; agent ops',
      'framework comes from node-agent-architecture.md.',
    ].join('\n'),
  },
  {
    file: 'docs/certificate-management.md',
    task: 'DOC: docs/certificate-management.md - Certificate management subsystem.\n' + [
      'Required sections: Certificate entity (domain-model.md 2.4); ACME architecture: control-plane',
      'ACME client, DNS-01 challenge FIRST (works for NAT-ed home servers + wildcards, no port-80',
      'requirement) via a DNSProvider interface (Cloudflare first, creds in Integration rows,',
      'encrypted); HTTP-01 via node nginx as later fallback; issuance flow (request -> order ->',
      'challenge -> issue -> store -> deliver); renewal (celery beat scan expires_at < 30d, reissue,',
      'delivery, failure alerts + incident); certificate storage (Fernet ciphertext columns, keys',
      'NEVER in API responses/logs/WS/audit/frontend - leak-path table); delivery to serving node via',
      'encrypted agent operation (secret minimization: only nodes serving routes using the cert);',
      'wildcard certificates; status/expiry tracking + TLS-expiry monitors tie-in; failure handling',
      '(DNS API failures, rate limits from Let Encrypt, stuck states); audit events (issued/renewed/',
      'failed/deployed).',
      'Mermaid: issuance sequence (control plane + DNS API + node agent).',
      'Ground: Fernet encrypt_str/decrypt_str exist (core/security.py); Integration entity is in',
      'domain-model.md 2.7; ops framework in node-agent-architecture.md.',
    ].join('\n'),
  },
  {
    file: 'docs/deployment-architecture.md',
    task: 'DOC: docs/deployment-architecture.md - Deployment architecture (target state).\n' + [
      'Required sections: honest current state (100% simulated runner, engine hard-instantiates the',
      'runner at two sites with no DI, RunContext lacks repository_url/default_branch/build_config/',
      'node addressing, secret resolution silently degrades to empty on failure - cite findings +',
      'code); target pipeline source->build->artifact->deploy->health->route->monitor; runner',
      'registry/DI fix; AgentDeploymentRunner implementing the EXISTING DeploymentRunner protocol',
      '(plan_steps/execute_step/StepLine) dispatching steps as agent operations, streaming StepLines',
      'back over the existing Redis deployment log channel; phased scope: Phase 6a = image-based',
      'deploys (agent pulls image, stops old, runs new with env/ports, healthcheck), Phase 6b =',
      'git-based build on node (docker build); step model table per phase; environments (project-',
      'scoped after Phase 2 promotion) and config layering (project config -> environment config ->',
      'deploy-time secret references, most specific wins); secret-resolution hardening: fail-closed,',
      'audit at resolution time; cancellation and per-step timeouts (current cancel is cooperative-',
      'only between steps); events/WS during runs; post-deploy hooks: route sync + auto-monitor',
      'creation; rollback semantics (new deployment re-deploying last good version - existing',
      'behavior kept); simulated runner stays for demo/CI, labeled.',
      'Mermaid: state machine, and agent-runner sequence.',
      'Current-state evidence (findings agent-8): engine.py hard instantiation, RunContext fields,',
      'StepName/STEP_ORDER, the -broken health hook, queue->worker->sweeper backstop.',
    ].join('\n'),
  },
  {
    file: 'docs/secrets-architecture.md',
    task: 'DOC: docs/secrets-architecture.md - Secrets and configuration.\n' + [
      'Required sections: current state (Fernet at rest via encrypt_str; global-or-project scope;',
      'rotation overwrites in place with version counter; metadata-only reads; deploy-time resolution',
      'via the secret-reference syntax; SILENT DEGRADE BUG: resolution failures yield empty dict and',
      'unresolved refs resolve to empty string - cite code); target scope model (org / project /',
      'environment layering per domain-model.md 2.5; resolution precedence); SecretVersion append-only',
      'history (rotation no longer destructive; rotation rollback); resolution authorization (who may',
      'trigger resolution = deploy permission chain, NOT secret.read; audit event at resolution time',
      'without values); fail-closed resolution policy; key hierarchy (single Fernet ENCRYPTION_KEY now;',
      'per-org DEK envelope design for later, KMS-ready); node delivery minimization (a node receives',
      'only secrets its assigned routes/services reference; encrypted delivery via agent op; node',
      'compromise blast radius); environment-config vs secrets boundary (what belongs where);',
      'leak-path table: API responses / logs / WS / audit metadata / frontend state / error messages -',
      'and the guard for each.',
      'Mermaid: resolution flow at deploy time.',
    ].join('\n'),
  },
  {
    file: 'docs/platform-security-model.md',
    task: 'DOC: docs/platform-security-model.md - Security model and threat model.\n' + [
      'Required sections: assets and trust boundaries (control plane, customer nodes, agents,',
      'secrets, certs); the tenant isolation model summary (pointer to multi-tenancy.md); THREAT',
      'MODEL TABLE covering at least: cross-tenant IDOR, WS cross-tenant subscription, background-job',
      'tenancy, agent token theft, node compromise, agent->control-plane attacks (forged',
      'heartbeats/facts), control-plane compromise blast radius, SSRF (endpoints, monitors, webhooks',
      '- existing ALLOW_PRIVATE_TARGETS guard), remote code execution (the operations whitelist as',
      'the mitigation; no shell), docker socket root-equivalence, nginx config injection, certificate',
      'abuse (issuing certs for domains you do not own - DNS verification as gate), domain takeover,',
      'secret access paths, privilege escalation (grants, custom roles, API keys), enrollment token',
      'brute force, deployment spam/cost abuse - columns: threat / who could invoke / authorization',
      'required / audited / failure behavior / cross-tenant impact;',
      'CURRENT-CODE HARDENING LIST (from findings, cite): silent secret-resolution degradation, WS',
      'global channel exposure, agent token non-revocation + 401 hot-loop, agent plain-HTTP transport',
      'option, rate limits keyed by IP only (NAT agent fleets share a bucket), Server.name global',
      'uniqueness, secrets resolution lacking per-user authorization on the engine path, audit rows',
      'lacking org/request-id; platform controls that carry over (argon2id, session rotation + reuse',
      'detection, fixed-window limiters, client-IP chain resolution, append-only audit with DB',
      'trigger); IDOR suite as CI gate; abuse prevention (org-scoped limiter dimension, enrollment',
      'throttles); incident response (node revocation playbook, key compromise playbook).',
      'This doc may REPEAT the hardening list in roadmap Phase 0 - keep the two lists consistent',
      '(the roadmap lists them as Phase 0 items).',
    ].join('\n'),
  },
  {
    file: 'docs/architecture.md',
    task: 'DOC: docs/architecture.md - UPDATE of the existing system-architecture document.\n' + [
      'This is an UPDATE of a 900-line existing doc. First READ the current docs/architecture.md',
      'fully, then REWRITE it so that:',
      '1. All ACCURATE current-state content is preserved (backend/frontend/agent/workers/redis',
      'channels/schemas/RBAC mechanics - the reader reports confirm most of it is accurate).',
      '2. KNOWN STALE CLAIMS are fixed: the Secure-cookie descriptions contradict the shipped',
      'X-Forwarded-Proto-derived behavior in four docs (README.md:162, architecture.md:300,',
      'development.md:93, troubleshooting.md:520-535) - fix the architecture.md instance against',
      'backend/app/api/v1/auth.py:27-43; fix any role-count claims (5 roles not 4); the rate limiter',
      'is fixed-window not token bucket.',
      '3. A new top section "Platform evolution" summarizes the multi-tenant target (control/data',
      'plane, org model) and links the new docs: platform-vision.md, domain-model.md, multi-tenancy.md,',
      'authorization.md, node-agent-architecture.md, domain-routing.md, certificate-management.md,',
      'deployment-architecture.md, secrets-architecture.md, platform-security-model.md,',
      'product-roadmap.md.',
      '4. Honesty box: deployments are simulated (SimulatedDeploymentRunner), sim:// monitors,',
      'docker_sim - with pointers to the roadmap phases that make them real.',
      '5. The ER/entity overview updated to the target domain model (org-scoped), marked',
      'existing/new/promoted.',
      'Keep the existing doc structure/tone (it is terse and factual). Do not delete runbook content',
      'that is still true. End with the updated doc-version note.',
    ].join('\n'),
  },
]

phase('Draft')
log('Drafting 7 documents in parallel, then verifying each')
const results = await pipeline(
  DOCS,
  d => agent(
    SPINE + '\n\nYOUR TASK:\n' + d.task + '\n\nWrite the complete document to ' + d.file + ' using the Write tool.',
    { label: 'draft:' + d.file.replace('docs/', ''), phase: 'Draft' },
  ),
  (draftRes, d) => agent(
    VERIFY_RULES + '\n\nDOC UNDER AUDIT: ' + d.file + '\n\nTASK THE DRAFTER WAS GIVEN:\n' + d.task,
    { label: 'verify:' + d.file.replace('docs/', ''), phase: 'Verify', schema: {
      type: 'object',
      required: ['doc', 'issues'],
      properties: {
        doc: { type: 'string' },
        issues: { type: 'array', maxItems: 20, items: {
          type: 'object',
          required: ['severity', 'issue'],
          properties: {
            severity: { type: 'string', enum: ['blocker', 'major', 'minor'] },
            issue: { type: 'string' },
            location: { type: 'string' },
          },
        } },
        verdict: { type: 'string', enum: ['solid', 'needs-fixes'] },
      },
    } },
  ),
  (verifyRes, d) => {
    if (!verifyRes || !verifyRes.issues || verifyRes.issues.length === 0) {
      return Promise.resolve({ doc: d.file, fixed: 0, note: 'clean - no fixes needed' })
    }
    const issuesJson = JSON.stringify(verifyRes.issues, null, 1)
    return agent(
      [
        'You are fixing verified issues in an architecture document for the NexusOps multi-tenant redesign.',
        'Repo: /home/emad/projects/nexusops. The doc ' + d.file + ' was audited against the spine docs',
        '(docs/platform-vision.md, docs/domain-model.md, docs/multi-tenancy.md, docs/authorization.md)',
        'and the repo. Fix EVERY issue below by editing ' + d.file + ' ONLY. Do not modify any other file.',
        'For claimed spine-doc contradictions, re-read the spine doc and fix this doc to match it.',
        'Re-check relevant code before changing code-grounding claims (path:line). Keep the doc structure;',
        'edit surgically rather than rewriting whole sections. After fixing, return one line per issue:',
        '"fixed: <short what>" or "wontfix: <reason>".',
        '',
        'ISSUES:',
        issuesJson,
      ].join('\n'),
      { label: 'fix:' + d.file.replace('docs/', ''), phase: 'Fix' },
    )
  },
)

return results
