"""initial schema

Revision ID: b5866787bde4
Revises: 
Create Date: 2026-08-23 22:25:17.176205

"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = 'b5866787bde4'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


AUDIT_IMMUTABILITY_TRIGGER = """
CREATE OR REPLACE FUNCTION nexusops_block_audit_mutation() RETURNS trigger AS $$
BEGIN
    RAISE EXCEPTION 'audit_logs is append-only (attempted %)', TG_OP;
END;
$$ LANGUAGE plpgsql;
"""

AUDIT_IMMUTABILITY_DROP = """
DROP FUNCTION IF EXISTS nexusops_block_audit_mutation() CASCADE;
"""


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alerts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('severity', sa.String(length=12), nullable=False),
    sa.Column('title', sa.String(length=240), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('resource_type', sa.String(length=48), nullable=True),
    sa.Column('resource_id', sa.String(length=72), nullable=True),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("severity IN ('INFO', 'WARNING', 'CRITICAL')", name=op.f('ck_alerts_severity_valid')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_alerts'))
    )
    op.create_index(op.f('ix_alerts_created_at'), 'alerts', ['created_at'], unique=False)
    op.create_index('ix_alerts_read_created', 'alerts', ['read_at', 'created_at'], unique=False)
    op.create_table('permissions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('codename', sa.String(length=96), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('group', sa.String(length=48), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_permissions')),
    sa.UniqueConstraint('codename', name=op.f('uq_permissions_codename'))
    )
    op.create_index(op.f('ix_permissions_created_at'), 'permissions', ['created_at'], unique=False)
    op.create_table('roles',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_roles')),
    sa.UniqueConstraint('name', name=op.f('uq_roles_name'))
    )
    op.create_index(op.f('ix_roles_created_at'), 'roles', ['created_at'], unique=False)
    op.create_table('servers',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('hostname', sa.String(length=255), nullable=False),
    sa.Column('ip_address', sa.String(length=64), nullable=False),
    sa.Column('os_name', sa.String(length=96), nullable=False),
    sa.Column('os_version', sa.String(length=96), nullable=False),
    sa.Column('arch', sa.String(length=32), nullable=False),
    sa.Column('environment', sa.String(length=32), nullable=False),
    sa.Column('location', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('cpu_cores', sa.Integer(), nullable=False),
    sa.Column('memory_total_mb', sa.Integer(), nullable=False),
    sa.Column('disk_total_gb', sa.Integer(), nullable=False),
    sa.Column('agent_version', sa.String(length=48), nullable=False),
    sa.Column('agent_token_hash', sa.String(length=64), nullable=True),
    sa.Column('agent_enrolled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_heartbeat_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('heartbeat_interval_seconds', sa.Integer(), nullable=False),
    sa.Column('offline_after_seconds', sa.Integer(), nullable=True),
    sa.Column('uptime_seconds', sa.BigInteger(), nullable=False),
    sa.Column('simulated', sa.Boolean(), nullable=False),
    sa.Column('extra', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('ONLINE', 'OFFLINE', 'DEGRADED', 'UNKNOWN')", name=op.f('ck_servers_status_valid')),
    sa.CheckConstraint('heartbeat_interval_seconds >= 5', name=op.f('ck_servers_heartbeat_interval_min')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_servers')),
    sa.UniqueConstraint('name', name=op.f('uq_servers_name'))
    )
    op.create_index(op.f('ix_servers_agent_token_hash'), 'servers', ['agent_token_hash'], unique=False)
    op.create_index(op.f('ix_servers_created_at'), 'servers', ['created_at'], unique=False)
    op.create_index(op.f('ix_servers_status'), 'servers', ['status'], unique=False)
    op.create_index('ix_servers_status_heartbeat', 'servers', ['status', 'last_heartbeat_at'], unique=False)
    op.create_table('tags',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('color', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tags')),
    sa.UniqueConstraint('name', name=op.f('uq_tags_name'))
    )
    op.create_index(op.f('ix_tags_created_at'), 'tags', ['created_at'], unique=False)
    op.create_table('docker_hosts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('server_id', sa.Uuid(), nullable=True),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('endpoint_url', sa.String(length=512), nullable=False),
    sa.Column('tls_verify', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('last_checked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['server_id'], ['servers.id'], name=op.f('fk_docker_hosts_server_id_servers'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_docker_hosts'))
    )
    op.create_index(op.f('ix_docker_hosts_created_at'), 'docker_hosts', ['created_at'], unique=False)
    op.create_index(op.f('ix_docker_hosts_server_id'), 'docker_hosts', ['server_id'], unique=False)
    op.create_index(op.f('ix_docker_hosts_status'), 'docker_hosts', ['status'], unique=False)
    op.create_table('metric_snapshots',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('server_id', sa.Uuid(), nullable=False),
    sa.Column('granularity', sa.String(length=8), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('cpu_percent', sa.Float(), nullable=False),
    sa.Column('mem_used_mb', sa.Float(), nullable=False),
    sa.Column('mem_percent', sa.Float(), nullable=False),
    sa.Column('disk_used_gb', sa.Float(), nullable=False),
    sa.Column('disk_percent', sa.Float(), nullable=False),
    sa.Column('net_rx_kb_s', sa.Float(), nullable=False),
    sa.Column('net_tx_kb_s', sa.Float(), nullable=False),
    sa.Column('load1', sa.Float(), nullable=False),
    sa.Column('uptime_seconds', sa.BigInteger(), nullable=False),
    sa.Column('extra', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.CheckConstraint("granularity IN ('RAW', 'HOURLY', 'DAILY')", name=op.f('ck_metric_snapshots_granularity_valid')),
    sa.ForeignKeyConstraint(['server_id'], ['servers.id'], name=op.f('fk_metric_snapshots_server_id_servers'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_metric_snapshots'))
    )
    op.create_index('ix_metrics_server_gran_time', 'metric_snapshots', ['server_id', 'granularity', 'recorded_at'], unique=False)
    op.create_table('role_permissions',
    sa.Column('role_id', sa.Uuid(), nullable=False),
    sa.Column('permission_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], name=op.f('fk_role_permissions_permission_id_permissions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name=op.f('fk_role_permissions_role_id_roles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('role_id', 'permission_id', name=op.f('pk_role_permissions'))
    )
    op.create_table('server_tags',
    sa.Column('server_id', sa.Uuid(), nullable=False),
    sa.Column('tag_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['server_id'], ['servers.id'], name=op.f('fk_server_tags_server_id_servers'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], name=op.f('fk_server_tags_tag_id_tags'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('server_id', 'tag_id', name=op.f('pk_server_tags'))
    )
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('full_name', sa.String(length=160), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superadmin', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('failed_login_attempts', sa.Integer(), nullable=False),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('role_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name=op.f('fk_users_role_id_roles'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_created_at'), 'users', ['created_at'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('api_keys',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('key_prefix', sa.String(length=24), nullable=False),
    sa.Column('key_hash', sa.String(length=64), nullable=False),
    sa.Column('scopes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_api_keys_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_api_keys')),
    sa.UniqueConstraint('key_hash', name=op.f('uq_api_keys_key_hash'))
    )
    op.create_index(op.f('ix_api_keys_created_at'), 'api_keys', ['created_at'], unique=False)
    op.create_index(op.f('ix_api_keys_user_id'), 'api_keys', ['user_id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.Column('actor_id', sa.Uuid(), nullable=True),
    sa.Column('actor_email', sa.String(length=320), nullable=False),
    sa.Column('action', sa.String(length=96), nullable=False),
    sa.Column('resource_type', sa.String(length=48), nullable=True),
    sa.Column('resource_id', sa.String(length=72), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=False),
    sa.Column('user_agent', sa.String(length=400), nullable=False),
    sa.Column('result', sa.String(length=12), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.CheckConstraint("result IN ('SUCCESS', 'DENIED', 'ERROR')", name=op.f('ck_audit_logs_result_valid')),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], name=op.f('fk_audit_logs_actor_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_logs'))
    )
    op.create_index('ix_audit_created_desc', 'audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_actor_id'), 'audit_logs', ['actor_id'], unique=False)
    op.create_table('container_images',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('docker_host_id', sa.Uuid(), nullable=False),
    sa.Column('image_id', sa.String(length=80), nullable=False),
    sa.Column('repo_tags', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('architecture', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['docker_host_id'], ['docker_hosts.id'], name=op.f('fk_container_images_docker_host_id_docker_hosts'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_container_images')),
    sa.UniqueConstraint('docker_host_id', 'image_id', name='uq_images_host_iid')
    )
    op.create_index(op.f('ix_container_images_created_at'), 'container_images', ['created_at'], unique=False)
    op.create_index(op.f('ix_container_images_docker_host_id'), 'container_images', ['docker_host_id'], unique=False)
    op.create_table('containers',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('docker_host_id', sa.Uuid(), nullable=False),
    sa.Column('server_id', sa.Uuid(), nullable=True),
    sa.Column('container_id', sa.String(length=72), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('image_ref', sa.String(length=300), nullable=False),
    sa.Column('command', sa.String(length=500), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('health', sa.String(length=12), nullable=False),
    sa.Column('ports', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('env_keys', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('labels', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('mounts', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('restart_count', sa.Integer(), nullable=False),
    sa.Column('cpu_percent', sa.Float(), nullable=True),
    sa.Column('mem_used_mb', sa.Float(), nullable=True),
    sa.Column('mem_limit_mb', sa.Float(), nullable=True),
    sa.Column('net_rx_kb_s', sa.Float(), nullable=True),
    sa.Column('net_tx_kb_s', sa.Float(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('simulated', sa.Boolean(), nullable=False),
    sa.CheckConstraint("health IN ('NONE', 'STARTING', 'HEALTHY', 'UNHEALTHY')", name=op.f('ck_containers_health_valid')),
    sa.CheckConstraint("status IN ('RUNNING', 'EXITED', 'PAUSED', 'CREATED', 'RESTARTING', 'DEAD', 'REMOVED')", name=op.f('ck_containers_status_valid')),
    sa.ForeignKeyConstraint(['docker_host_id'], ['docker_hosts.id'], name=op.f('fk_containers_docker_host_id_docker_hosts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['server_id'], ['servers.id'], name=op.f('fk_containers_server_id_servers'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_containers')),
    sa.UniqueConstraint('docker_host_id', 'container_id', name='uq_containers_host_cid')
    )
    op.create_index(op.f('ix_containers_docker_host_id'), 'containers', ['docker_host_id'], unique=False)
    op.create_index(op.f('ix_containers_server_id'), 'containers', ['server_id'], unique=False)
    op.create_index(op.f('ix_containers_status'), 'containers', ['status'], unique=False)
    op.create_index('ix_containers_status_name', 'containers', ['status', 'name'], unique=False)
    op.create_table('notification_channels',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('type', sa.String(length=16), nullable=False),
    sa.Column('config_ciphertext', sa.Text(), nullable=False),
    sa.Column('display_target', sa.String(length=300), nullable=False),
    sa.Column('events', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_by_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("type IN ('EMAIL', 'WEBHOOK')", name=op.f('ck_notification_channels_type_valid')),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_notification_channels_created_by_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notification_channels'))
    )
    op.create_index(op.f('ix_notification_channels_created_at'), 'notification_channels', ['created_at'], unique=False)
    op.create_table('projects',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('repository_url', sa.String(length=500), nullable=False),
    sa.Column('default_branch', sa.String(length=120), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('fk_projects_owner_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_projects')),
    sa.UniqueConstraint('name', name=op.f('uq_projects_name'))
    )
    op.create_index(op.f('ix_projects_created_at'), 'projects', ['created_at'], unique=False)
    op.create_table('server_credentials',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('server_id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('port', sa.Integer(), nullable=False),
    sa.Column('secret_ciphertext', sa.Text(), nullable=False),
    sa.Column('fingerprint', sa.String(length=128), nullable=False),
    sa.Column('created_by_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_server_credentials_created_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['server_id'], ['servers.id'], name=op.f('fk_server_credentials_server_id_servers'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_server_credentials'))
    )
    op.create_index(op.f('ix_server_credentials_created_at'), 'server_credentials', ['created_at'], unique=False)
    op.create_index(op.f('ix_server_credentials_server_id'), 'server_credentials', ['server_id'], unique=False)
    op.create_table('sessions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('ip_address', sa.String(length=64), nullable=False),
    sa.Column('user_agent', sa.Text(), nullable=False),
    sa.Column('device_label', sa.String(length=120), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_reason', sa.String(length=120), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_sessions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sessions'))
    )
    op.create_index(op.f('ix_sessions_created_at'), 'sessions', ['created_at'], unique=False)
    op.create_index(op.f('ix_sessions_user_id'), 'sessions', ['user_id'], unique=False)
    op.create_table('system_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.Column('type', sa.String(length=64), nullable=False),
    sa.Column('level', sa.String(length=12), nullable=False),
    sa.Column('message', sa.String(length=500), nullable=False),
    sa.Column('actor_id', sa.Uuid(), nullable=True),
    sa.Column('actor_type', sa.String(length=12), nullable=False),
    sa.Column('resource_type', sa.String(length=48), nullable=True),
    sa.Column('resource_id', sa.String(length=72), nullable=True),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('dedup_key', sa.String(length=160), nullable=True),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], name=op.f('fk_system_events_actor_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_system_events')),
    sa.UniqueConstraint('dedup_key', name='uq_system_events_dedup_key')
    )
    op.create_index('ix_events_created_desc', 'system_events', ['created_at'], unique=False)
    op.create_index('ix_events_type_created', 'system_events', ['type', 'created_at'], unique=False)
    op.create_index(op.f('ix_system_events_type'), 'system_events', ['type'], unique=False)
    op.create_table('applications',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('slug', sa.String(length=140), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('repository_url', sa.String(length=500), nullable=False),
    sa.Column('build_config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('current_version', sa.String(length=160), nullable=True),
    sa.Column('current_deployment_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['current_deployment_id'], ['deployments.id'], name=op.f('fk_applications_current_deployment_id_deployments'), ondelete='SET NULL', use_alter=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_applications_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_applications')),
    sa.UniqueConstraint('project_id', 'name', name='uq_applications_project_name')
    )
    op.create_index(op.f('ix_applications_created_at'), 'applications', ['created_at'], unique=False)
    op.create_index(op.f('ix_applications_project_id'), 'applications', ['project_id'], unique=False)
    op.create_table('monitors',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.Column('url', sa.String(length=1000), nullable=False),
    sa.Column('method', sa.String(length=10), nullable=False),
    sa.Column('interval_seconds', sa.Integer(), nullable=False),
    sa.Column('timeout_seconds', sa.Float(), nullable=False),
    sa.Column('expected_status', sa.Integer(), nullable=False),
    sa.Column('expected_body', sa.Text(), nullable=True),
    sa.Column('headers', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('skip_tls_verify', sa.Boolean(), nullable=False),
    sa.Column('follow_redirects', sa.Boolean(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('consecutive_failures', sa.Integer(), nullable=False),
    sa.Column('consecutive_successes', sa.Integer(), nullable=False),
    sa.Column('next_check_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_check_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_success_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_failure_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failure_threshold', sa.Integer(), nullable=False),
    sa.Column('success_threshold', sa.Integer(), nullable=False),
    sa.Column('created_by_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('PENDING', 'UP', 'DOWN', 'PAUSED')", name=op.f('ck_monitors_status_valid')),
    sa.CheckConstraint('interval_seconds >= 10', name=op.f('ck_monitors_interval_min')),
    sa.CheckConstraint('timeout_seconds > 0 AND timeout_seconds <= 60', name=op.f('ck_monitors_timeout_bounds')),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_monitors_created_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_monitors_project_id_projects'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_monitors'))
    )
    op.create_index(op.f('ix_monitors_created_at'), 'monitors', ['created_at'], unique=False)
    op.create_index('ix_monitors_next_check', 'monitors', ['enabled', 'next_check_at'], unique=False)
    op.create_index(op.f('ix_monitors_project_id'), 'monitors', ['project_id'], unique=False)
    op.create_index(op.f('ix_monitors_status'), 'monitors', ['status'], unique=False)
    op.create_table('refresh_tokens',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('superseded_by_id', sa.Uuid(), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], name=op.f('fk_refresh_tokens_session_id_sessions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_refresh_tokens')),
    sa.UniqueConstraint('token_hash', name=op.f('uq_refresh_tokens_token_hash'))
    )
    op.create_index(op.f('ix_refresh_tokens_created_at'), 'refresh_tokens', ['created_at'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_session_id'), 'refresh_tokens', ['session_id'], unique=False)
    op.create_table('secrets',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.Column('key', sa.String(length=160), nullable=False),
    sa.Column('ciphertext', sa.Text(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('digest', sa.String(length=16), nullable=False),
    sa.Column('description', sa.String(length=300), nullable=False),
    sa.Column('rotated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rotated_by_id', sa.Uuid(), nullable=True),
    sa.Column('created_by_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_secrets_created_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_secrets_project_id_projects'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['rotated_by_id'], ['users.id'], name=op.f('fk_secrets_rotated_by_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_secrets')),
    sa.UniqueConstraint('project_id', 'key', name='uq_secrets_project_key')
    )
    op.create_index(op.f('ix_secrets_created_at'), 'secrets', ['created_at'], unique=False)
    op.create_index(op.f('ix_secrets_project_id'), 'secrets', ['project_id'], unique=False)
    op.create_index('ux_secrets_global_key', 'secrets', ['key'], unique=True, postgresql_where=sa.text('project_id IS NULL'))
    op.create_table('deployment_environments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('application_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('slug', sa.String(length=84), nullable=False),
    sa.Column('server_id', sa.Uuid(), nullable=True),
    sa.Column('healthcheck_path', sa.String(length=300), nullable=False),
    sa.Column('auto_deploy', sa.Boolean(), nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], name=op.f('fk_deployment_environments_application_id_applications'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['server_id'], ['servers.id'], name=op.f('fk_deployment_environments_server_id_servers'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_deployment_environments')),
    sa.UniqueConstraint('application_id', 'name', name='uq_envs_application_name')
    )
    op.create_index(op.f('ix_deployment_environments_application_id'), 'deployment_environments', ['application_id'], unique=False)
    op.create_index(op.f('ix_deployment_environments_created_at'), 'deployment_environments', ['created_at'], unique=False)
    op.create_table('incidents',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('monitor_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=240), nullable=False),
    sa.Column('severity', sa.String(length=12), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('failure_count', sa.Integer(), nullable=False),
    sa.Column('opened_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('detected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('acknowledged_by_id', sa.Uuid(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolution', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("severity IN ('CRITICAL', 'MAJOR', 'MINOR', 'WARNING')", name=op.f('ck_incidents_severity_valid')),
    sa.CheckConstraint("status IN ('OPEN', 'ACKNOWLEDGED', 'RESOLVED')", name=op.f('ck_incidents_status_valid')),
    sa.ForeignKeyConstraint(['acknowledged_by_id'], ['users.id'], name=op.f('fk_incidents_acknowledged_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['monitor_id'], ['monitors.id'], name=op.f('fk_incidents_monitor_id_monitors'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_incidents'))
    )
    op.create_index(op.f('ix_incidents_created_at'), 'incidents', ['created_at'], unique=False)
    op.create_index(op.f('ix_incidents_monitor_id'), 'incidents', ['monitor_id'], unique=False)
    op.create_index('ix_incidents_monitor_status', 'incidents', ['monitor_id', 'status'], unique=False)
    op.create_index('ix_incidents_status_opened', 'incidents', ['status', 'opened_at'], unique=False)
    op.create_table('monitor_checks',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('monitor_id', sa.Uuid(), nullable=False),
    sa.Column('checked_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('result', sa.String(length=12), nullable=False),
    sa.Column('response_time_ms', sa.Float(), nullable=True),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('error', sa.String(length=500), nullable=False),
    sa.CheckConstraint("result IN ('SUCCESS', 'FAILURE', 'TIMEOUT', 'ERROR')", name=op.f('ck_monitor_checks_result_valid')),
    sa.ForeignKeyConstraint(['monitor_id'], ['monitors.id'], name=op.f('fk_monitor_checks_monitor_id_monitors'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_monitor_checks'))
    )
    op.create_index('ix_checks_monitor_time', 'monitor_checks', ['monitor_id', 'checked_at'], unique=False)
    op.create_index(op.f('ix_monitor_checks_result'), 'monitor_checks', ['result'], unique=False)
    op.create_table('deployments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('application_id', sa.Uuid(), nullable=False),
    sa.Column('environment_id', sa.Uuid(), nullable=False),
    sa.Column('version', sa.String(length=160), nullable=False),
    sa.Column('git_commit', sa.String(length=80), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('trigger', sa.String(length=16), nullable=False),
    sa.Column('triggered_by_id', sa.Uuid(), nullable=True),
    sa.Column('is_rollback', sa.Boolean(), nullable=False),
    sa.Column('rollback_of_id', sa.Uuid(), nullable=True),
    sa.Column('queued_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_ms', sa.BigInteger(), nullable=True),
    sa.Column('failure_reason', sa.Text(), nullable=False),
    sa.Column('cancel_requested', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('QUEUED', 'RUNNING', 'SUCCESS', 'FAILED', 'CANCELLED', 'ROLLBACK')", name=op.f('ck_deployments_status_valid')),
    sa.CheckConstraint("trigger IN ('MANUAL', 'API', 'ROLLBACK', 'AUTO')", name=op.f('ck_deployments_trigger_valid')),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], name=op.f('fk_deployments_application_id_applications'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['environment_id'], ['deployment_environments.id'], name=op.f('fk_deployments_environment_id_deployment_environments'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['rollback_of_id'], ['deployments.id'], name=op.f('fk_deployments_rollback_of_id_deployments'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['triggered_by_id'], ['users.id'], name=op.f('fk_deployments_triggered_by_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_deployments')),
    sa.UniqueConstraint('application_id', 'number', name='uq_deployments_app_number')
    )
    op.create_index(op.f('ix_deployments_application_id'), 'deployments', ['application_id'], unique=False)
    op.create_index(op.f('ix_deployments_created_at'), 'deployments', ['created_at'], unique=False)
    op.create_index('ix_deployments_environment_created', 'deployments', ['environment_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_deployments_status'), 'deployments', ['status'], unique=False)
    op.create_index('ix_deployments_status_created', 'deployments', ['status', 'created_at'], unique=False)
    op.create_table('incident_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('incident_id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.String(length=24), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('actor_id', sa.Uuid(), nullable=True),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], name=op.f('fk_incident_events_actor_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], name=op.f('fk_incident_events_incident_id_incidents'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_incident_events'))
    )
    op.create_index('ix_incident_events_incident_time', 'incident_events', ['incident_id', 'occurred_at'], unique=False)
    op.create_table('notification_deliveries',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('channel_id', sa.Uuid(), nullable=False),
    sa.Column('event_id', sa.Uuid(), nullable=True),
    sa.Column('incident_id', sa.Uuid(), nullable=True),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('subject', sa.String(length=300), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('next_retry_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('PENDING', 'SENT', 'FAILED', 'SKIPPED')", name=op.f('ck_notification_deliveries_status_valid')),
    sa.CheckConstraint('attempts >= 0', name=op.f('ck_notification_deliveries_attempts_nonneg')),
    sa.ForeignKeyConstraint(['channel_id'], ['notification_channels.id'], name=op.f('fk_notification_deliveries_channel_id_notification_channels'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['event_id'], ['system_events.id'], name=op.f('fk_notification_deliveries_event_id_system_events'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], name=op.f('fk_notification_deliveries_incident_id_incidents'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notification_deliveries'))
    )
    op.create_index('ix_deliveries_status_retry', 'notification_deliveries', ['status', 'next_retry_at'], unique=False)
    op.create_index(op.f('ix_notification_deliveries_channel_id'), 'notification_deliveries', ['channel_id'], unique=False)
    op.create_table('deployment_steps',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('deployment_id', sa.Uuid(), nullable=False),
    sa.Column('idx', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('output', sa.Text(), nullable=False),
    sa.Column('error', sa.Text(), nullable=False),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('PENDING', 'RUNNING', 'SUCCESS', 'FAILED', 'SKIPPED', 'CANCELLED')", name=op.f('ck_deployment_steps_status_valid')),
    sa.ForeignKeyConstraint(['deployment_id'], ['deployments.id'], name=op.f('fk_deployment_steps_deployment_id_deployments'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_deployment_steps')),
    sa.UniqueConstraint('deployment_id', 'idx', name='uq_steps_deployment_idx')
    )
    op.create_index(op.f('ix_deployment_steps_deployment_id'), 'deployment_steps', ['deployment_id'], unique=False)
    op.create_table('log_entries',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('container_id', sa.Uuid(), nullable=True),
    sa.Column('deployment_id', sa.Uuid(), nullable=True),
    sa.Column('server_id', sa.Uuid(), nullable=True),
    sa.Column('stream', sa.String(length=8), nullable=False),
    sa.Column('level', sa.String(length=8), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['container_id'], ['containers.id'], name=op.f('fk_log_entries_container_id_containers'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['deployment_id'], ['deployments.id'], name=op.f('fk_log_entries_deployment_id_deployments'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['server_id'], ['servers.id'], name=op.f('fk_log_entries_server_id_servers'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_log_entries'))
    )
    op.create_index('ix_logs_container_ts', 'log_entries', ['container_id', 'ts'], unique=False)
    op.create_index('ix_logs_deployment', 'log_entries', ['deployment_id', 'id'], unique=False)
    # ### end Alembic commands ###

    # Audit trail is append-only, enforced by the database itself — even a
    # compromised application role cannot rewrite history.
    op.execute(AUDIT_IMMUTABILITY_TRIGGER)
    op.execute(
        """
        CREATE TRIGGER audit_logs_no_update BEFORE UPDATE OR DELETE ON audit_logs
        FOR EACH ROW EXECUTE FUNCTION nexusops_block_audit_mutation();
        """
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_logs_deployment', table_name='log_entries')
    op.drop_index('ix_logs_container_ts', table_name='log_entries')
    op.drop_table('log_entries')
    op.drop_index(op.f('ix_deployment_steps_deployment_id'), table_name='deployment_steps')
    op.drop_table('deployment_steps')
    op.drop_index(op.f('ix_notification_deliveries_channel_id'), table_name='notification_deliveries')
    op.drop_index('ix_deliveries_status_retry', table_name='notification_deliveries')
    op.drop_table('notification_deliveries')
    op.drop_index('ix_incident_events_incident_time', table_name='incident_events')
    op.drop_table('incident_events')
    op.drop_index('ix_deployments_status_created', table_name='deployments')
    op.drop_index(op.f('ix_deployments_status'), table_name='deployments')
    op.drop_index('ix_deployments_environment_created', table_name='deployments')
    op.drop_index(op.f('ix_deployments_created_at'), table_name='deployments')
    op.drop_index(op.f('ix_deployments_application_id'), table_name='deployments')
    op.drop_table('deployments')
    op.drop_index(op.f('ix_monitor_checks_result'), table_name='monitor_checks')
    op.drop_index('ix_checks_monitor_time', table_name='monitor_checks')
    op.drop_table('monitor_checks')
    op.drop_index('ix_incidents_status_opened', table_name='incidents')
    op.drop_index('ix_incidents_monitor_status', table_name='incidents')
    op.drop_index(op.f('ix_incidents_monitor_id'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_created_at'), table_name='incidents')
    op.drop_table('incidents')
    op.drop_index(op.f('ix_deployment_environments_created_at'), table_name='deployment_environments')
    op.drop_index(op.f('ix_deployment_environments_application_id'), table_name='deployment_environments')
    op.drop_table('deployment_environments')
    op.drop_index('ux_secrets_global_key', table_name='secrets', postgresql_where=sa.text('project_id IS NULL'))
    op.drop_index(op.f('ix_secrets_project_id'), table_name='secrets')
    op.drop_index(op.f('ix_secrets_created_at'), table_name='secrets')
    op.drop_table('secrets')
    op.drop_index(op.f('ix_refresh_tokens_session_id'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_created_at'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index(op.f('ix_monitors_status'), table_name='monitors')
    op.drop_index(op.f('ix_monitors_project_id'), table_name='monitors')
    op.drop_index('ix_monitors_next_check', table_name='monitors')
    op.drop_index(op.f('ix_monitors_created_at'), table_name='monitors')
    op.drop_table('monitors')
    op.drop_index(op.f('ix_applications_project_id'), table_name='applications')
    op.drop_index(op.f('ix_applications_created_at'), table_name='applications')
    op.drop_table('applications')
    op.drop_index(op.f('ix_system_events_type'), table_name='system_events')
    op.drop_index('ix_events_type_created', table_name='system_events')
    op.drop_index('ix_events_created_desc', table_name='system_events')
    op.drop_table('system_events')
    op.drop_index(op.f('ix_sessions_user_id'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_created_at'), table_name='sessions')
    op.drop_table('sessions')
    op.drop_index(op.f('ix_server_credentials_server_id'), table_name='server_credentials')
    op.drop_index(op.f('ix_server_credentials_created_at'), table_name='server_credentials')
    op.drop_table('server_credentials')
    op.drop_index(op.f('ix_projects_created_at'), table_name='projects')
    op.drop_table('projects')
    op.drop_index(op.f('ix_notification_channels_created_at'), table_name='notification_channels')
    op.drop_table('notification_channels')
    op.drop_index('ix_containers_status_name', table_name='containers')
    op.drop_index(op.f('ix_containers_status'), table_name='containers')
    op.drop_index(op.f('ix_containers_server_id'), table_name='containers')
    op.drop_index(op.f('ix_containers_docker_host_id'), table_name='containers')
    op.drop_table('containers')
    op.drop_index(op.f('ix_container_images_docker_host_id'), table_name='container_images')
    op.drop_index(op.f('ix_container_images_created_at'), table_name='container_images')
    op.drop_table('container_images')
    op.drop_index(op.f('ix_audit_logs_actor_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_index('ix_audit_created_desc', table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_api_keys_user_id'), table_name='api_keys')
    op.drop_index(op.f('ix_api_keys_created_at'), table_name='api_keys')
    op.drop_table('api_keys')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_created_at'), table_name='users')
    op.drop_table('users')
    op.drop_table('server_tags')
    op.drop_table('role_permissions')
    op.drop_index('ix_metrics_server_gran_time', table_name='metric_snapshots')
    op.drop_table('metric_snapshots')
    op.drop_index(op.f('ix_docker_hosts_status'), table_name='docker_hosts')
    op.drop_index(op.f('ix_docker_hosts_server_id'), table_name='docker_hosts')
    op.drop_index(op.f('ix_docker_hosts_created_at'), table_name='docker_hosts')
    op.drop_table('docker_hosts')
    op.drop_index(op.f('ix_tags_created_at'), table_name='tags')
    op.drop_table('tags')
    op.drop_index('ix_servers_status_heartbeat', table_name='servers')
    op.drop_index(op.f('ix_servers_status'), table_name='servers')
    op.drop_index(op.f('ix_servers_created_at'), table_name='servers')
    op.drop_index(op.f('ix_servers_agent_token_hash'), table_name='servers')
    op.drop_table('servers')
    op.drop_index(op.f('ix_roles_created_at'), table_name='roles')
    op.drop_table('roles')
    op.drop_index(op.f('ix_permissions_created_at'), table_name='permissions')
    op.drop_table('permissions')
    op.drop_index('ix_alerts_read_created', table_name='alerts')
    op.drop_index(op.f('ix_alerts_created_at'), table_name='alerts')
    op.drop_table('alerts')
    # ### end Alembic commands ###
    op.execute(AUDIT_IMMUTABILITY_DROP)
